Kunstmaan/KunstmaanBundlesStandardEdition

- app/config/config_base.yml
added server_version to set the doctrine.server_version parameter added in parameters.yml.
> temporary fix issue #110 dbal 2.5

- app/SymfonyStandard/RootPackageInstallSubscriber.php
We don't need the symfony acmebundle here, we have our own demosite generation, and the AcmeBundle breaks the security.yml file.
> [CreateProject] Do not ask for the installation of the AcmeBundle anymore

- web/robots.txt
Removed robots.txt to default enable backend configuration.
> Remove robots.txt to allow backend management

- .travis.yml
- behat.yml
This makes the travis behat tests run again
> Make Travis tests run again

- app/config/parameters.yml.dist
> Fixed parameters.yml.dist to show right analytics url

- app/config/config_prod.yml
| Fixed tickets | /
See http://symfony.com/doc/current/cookbook/logging/monolog_email.html
> [Logging] Do not log 404s in the prod.log file

- .travis.yml
Also added configuration to test other databases (sqlite and postgres added to the allow_failures), and added elasticsearch dependency
> [Continuous Integration] Added travis configuration to test the master branch of the bundles cms

- app/AppKernel.php
> [LeadGenerationBundle] added LeadGenerationBundle to AppKernel

- composer.json
> Fix monolog version dependency to make it possible to install kunstmaanbundlecms 3.2.*

- .travis.yml
Otherwise the generatorbundle is not loaded in the AppKernel.
> Fixtures should run in dev environment

- composer.json
> [Dependencies] [WIP (waiting for tests)] Fix doctrine migrations dependency in composer.json

- app/config/security.yml
| Fixed tickets | https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/915
> [Config] fix security encoders

- app/config/config.yml
- app/config/routing.yml
Should be merged together with https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/932
> [MediaBundle] Update LiipImagineBundle to v1.4.3

- .travis.yml
- composer.json
This fixes the 'requested a non-existent service "fos_user.doctrine_registry"' issue.
> Fix composer.json FOSUserBundle requirements

- .travis.yml
- composer.json
> [Travis] Enable behat testing

- .travis.yml
> [Travis]: add support for php 7 

- app/config/config_prod.yml
- app/config/config_staging.yml
> [Config]: change admin path for fos_http_cache

- setup_project.sh
> [Setup] One command to create a new project

- app/config/security.singlelang.yml
Fix: https://github.com/Kunstmaan/KunstmaanBundlesStandardEdition/commit/2c7a9e2ead8562404b81b9702151e423bd0d6c3e
> Removed JmsSecurityExtra bundle

- composer.json
| Q        | A           
| -------- | --------
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Fixed tickets | |
> [Composer] fix cmf routing dependency

- composer.json
Depends on https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1270 
First the above pull request needs to be approved.
> Add AdminBundle composer post-install script in composer.json

- composer.json
| Fixed tickets | #1272 of KunstmaanBundlesCms
https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/1272
> [Composer]: change raven to sentry

- app/config/routing.yml
The main sitemap file should be /sitemap.xml
> Fix sitemap index path

- composer.json
Spork is not maintained anymore for a long time..
> [Composer]: remove spork

- composer.json
Lock fos-user version and remove spork.
> [Composer]: lock fos-user version

- composer.json
Already defined in KunstmaanBundlesCms
> [Composer]: remove fosuser from standard edition

- composer.json
- composer.lock
This will fix the cmf routing bundle problem
> fix composer and update lockfile

- app/config/config.yml
Could be merged after the relevant pull request in bundles is merged.
> Insert new configuration for the new pagepart chooser view

- setup_project.sh
No need for asset commands when this PR is merged:
https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1510
> update setup_project script

- app/config/config_base.yml
- app/config/config_dev.yml
- app/config/security.singlelang.yml
- app/config/security.yml
- web/app.php
- web/app_dev.php
On a clean install we generate some deprecations out of the box. This PR fixes some of those deprecations.
> [Config] Fixed symfony deprecations in standard edition

- app/config/config.yml
> [Config] Set sql mode to prevent group by errors

- app/config/config.yml
- app/config/config_prod.yml
- app/config/config_staging.yml
> [Config] Fix cache directory location

- app/AppKernel.php
- app/config/config.yml
- app/config/config_base.yml
- app/config/config_dev.yml
- app/config/config_test.yml
- app/config/parameters.yml.dist
- composer.json
- composer.lock
KunstmaanCMS does not need assetic anymore so it was removed as a dependency. I also updated the dependencies of the standard edtion and removed FOSUser since it's a dependency of the CMS and setting it here is just redundant
> [Config][Composer] Remove assetic from kernel and config + updated composer

- .travis/before_script.sh
Travis needs to update the dependencies when running from a cronjob. Otherwise the runs are pointless.
> [Travis] Update deps on cron runs

- composer.json
- composer.lock
Follow up PR for Kunstmaan/KunstmaanBundlesCMS#2025
> Add the symfony/swiftmailer-bundle dependency to the standard edition instead of the bundle-cms package

- composer.json
- composer.lock
Follow up PR for Kunstmaan/KunstmaanBundlesCMS#2061
> Add the symfony/monolog-bundle dependency to the standard edition instead of the bundle-cms package
