Kunstmaan/KunstmaanBundlesStandardEdition

- app/config/config_base.yml
- composer.json
default email validator is as of sf2.5 non-strict and allows invalid mail addresses.
> added strict validation

- app/config/routing.singlelang.yml
- app/config/routing.yml
| BC breaks?    | yes
| Fixed tickets | #302, #283
Adding the robots.txt management in the bundlesCMS needed some extra routes.
They will be added for future project in this PR.
> [SeoBundle] Robots.txt management needs extra routes

- app/config/routing.yml
This strange error is the result of using tabs instead of spaces in routing.yml
> [Install] Fix circular dependency problem on routing.yml > routing_dev.yml > routing.yml

- .travis.yml
As the bundles does not support 5.3 anymore, the standard edition also does not have to test it.
> [CI] Drop php 5.3 support in travis build configuration

- composer.json
Update phpunit to the same version as the bundles use. That way the bundle's unit tests could be run without much fuss.
> phpunit 4.4 to be able to run the kuma bundles tests

- composer.json
Symfony 2.7 gives deprecated errors and also a circular reference error.
We need to fix this before we are able to allow Symfony 2.7.
> locked Symfony on 2.6.9

- composer.json
The standard edition should use the current standards, and move to PSR-4 (cfr. http://www.php-fig.org/psr/psr-0/).
> Move to psr-4 as psr-0 is deprecated

- web/app.php
Because the ApcClassLoader code in `web/app.php` is enabled by default in Kunstmaan's 'StandardEdition' (when APC is available) I would suggest to update those lines to match Symfony 2.5-2.7's 'StandardEdition'.
```php
$apcLoader = new ApcClassLoader(sha1(__FILE__), $loader);
// ^ new vs old v
$apcLoader = new ApcClassLoader('sf2', $loader);
```
We are running some test apps on the same VM, with shared PHP instance (mod_php) and this caused quite some trouble and head-scratching.
Since we know this `sf2` perfix was the issue, we've updated those strings to be unique, but I think using the `sha1(__FILE__)` would be a safer default.
This change was introduced in Symfony's StandardEdition v2.5 and is there since.
> Update app.php ApcClassLoader code and comment to match Symfony >2.5

- app/config/config.yml
Before generating the default admin user, a placeholder for the generated password should be added to the app/resources/config.yml file.
The admin user is generated by running: app/console doctrine:fixtures:load. The new password will be displayed on the console to the user and the -adminpwd- placeholder will be replaced by the generated password.
> Add placeholder for generated password

- composer.json
| Fixed tickets | n/a
PSR-4 path to `SymfonyStandard` is incorrect
It was simply replaced at b38fd73b1cb38c9bdf6e50aa3a2996d0e43a4f9a `psr-0` with `psr-4` but it additionally requires fixing the path to the namespace.
> PSR-4 path to `SymfonyStandard` is incorrect

- app/config/config.yml
| BC breaks?    | yes
| Fixed tickets | none
`gedmo.listener.tree` was removed from NodeBudle in https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/846 and needs to by defined in application config.
> Add gedmo.listener.tree definition to config.yml

- app/config/config.yml
When moving onwards symfony 2.8, cookie_httponly needs to be set to false. If not, any scripting language like javascript, can not access the cookie variable.
See https://github.com/symfony/symfony/blob/2.8/UPGRADE-2.8.md#frameworkbundle
> Set cookie_httponly to false

- app/config/config_prod.yml
- app/config/config_staging.yml
The ability to pass apc as the framework.validation.cache configuration key value is deprecated, and will be removed in 3.0. Use validator.mapping.cache.doctrine.apc instead
See https://github.com/symfony/symfony/blob/2.8/UPGRADE-2.8.md#frameworkbundle
> Use validator.mapping.cache.doctrine.apc for apc caching

- app/config/config.yml
These image filters need to be present in the config file for srcset in ImagePagePart to work.
The template will crash if filters are not found.
> [Config] Added filters for srcset in ImagePagePart to config

- app/config/routing.singlelang.yml
Fix the https://github.com/Kunstmaan/KunstmaanBundlesStandardEdition/commit/7949dbf2dbc83c5d3d1a90fde880f9076552076a commit.
> Update LiipImagineBundle to v1.4.3 (fix)

- composer.json
Needed because when adding it only to the KunstmaanBundlesCms it will not be installed because of our minimum stability requirement.
> [Composer]: add fos-user beta to standard edition

- app/config/routing.yml
If "locking for entities"[Kunstmaan/KunstmaanBundlesCMS#1384] is merged in kunstmaanbundles, AdminListBundle now has a controller with an action and its routing.yml needs to be referenced
> [AdminListBundle] new routing defined

- app/config/config_prod.yml
- app/config/config_staging.yml
- app/config/parameters.yml.dist
The upgrade of the liip imagine bundle can not resolve cache paths with symbolic links. Therefore it's a good case to add the filesystem data_root parameter of liip_imagine as a parameter. When installing the standard edition, this parameter will be requested. If you run your website without the use of a symbolic link to the web directory, there will be no problem.
> [Config] add parameter to change liip imagine data root

- web/app.php
User Deprecated: The Symfony\Component\HttpFoundation\Request::setTrustedProxies() method expects a bit field of Request::HEADER_* as second argument since version 3.3. Defining it will be required in 4.0.
> SetTrustedProxies requires second argument

- app/config/config.yml
- app/config/parameters.yml.dist
With the updated version of FOS UserBundle there is extra config required. https://symfony.com/doc/master/bundles/FOSUserBundle/index.html#step-5-configure-the-fosuserbundle
> [Config] added fos user required email parameters

- .travis.yml
- .travis/after_failure.sh
- .travis/before_install.sh
- .travis/before_script.sh
- .travis/install.sh
- .travis/script.sh
- behat.yml
This PR finishes my work I started at the kumathon. It's a refactor the travis build config. Overview of all changes:
- Switch to the `sudo: false` aka container based to speedup the startup of the builds
- Setup travis caches to speed up build. With this we cut of +/- 4min of each build (for php5 even more)
- Use the pre-installed chrome to make the build invironment more reliable and predictable.
- Cache the selenium and chrome driver download
- I've added extra check to validate code/twig/security etc
- Lint the yaml config files in `app/config`
- Lint the twig files generated during bundle setup
- Check our composer.lock on the usage of libraries with security vulnerabilities
- On build failure we now also upload the logs files (behat, selenium, application). This in combination with …
> [Travis] Refactor travis build config and implement extra features/checks

- composer.json
- composer.lock
I've removed this dependency from the bundles package, but it should be present in the project itself to allow executing the composer post install/update scripts. See Kunstmaan/KunstmaanBundlesCMS#2023
> Add sensio distribution bundle

- composer.lock
Update `symfony/symfony` from `v3.4.11` to `v3.4.14` to get the latest security patches. Travis build will also fail when there are packages with security vulnerabilities.
See [CVE-2018-14773](https://symfony.com/blog/cve-2018-14773-remove-support-for-legacy-and-risky-http-headers) and [CVE-2018-14774](https://symfony.com/blog/cve-2018-14774-possible-host-header-injection-when-using-httpcache)
> Update symfony/symfony to latest version for security patches

- .travis.yml
- composer.json
- composer.lock
We've bumped the minimum version of php to 7.1 in v5.2. See Kunstmaan/KunstmaanBundlesCMS#2090
> Remove unsupported php versions from travis build matrix
